import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiOutlineInstagram,
  AiFillHtml5,
  AiFillGithub
} from "react-icons/ai";
import {
  DiPython,DiCss3,DiJava,DiPhotoshop,DiIllustrator
} from "react-icons/di";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/me.png";
import Image from "next/image";
import c1 from '../public/c1.png'
import c2 from '../public/c2.png'
import c3 from '../public/c3.png'
import c4 from '../public/c4.png'
import c5 from '../public/c5.png'
import Link from 'next/link'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? " ": "dark"}>
      <Head>
        <title>nikhilesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">NIKHILESH</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl ">
              Nikhilesh Anand Thakur
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Link href="https://www.linkedin.com/in/nikhilesh-thakur-5b490b1b8/"><AiFillLinkedin/></Link>
              <Link href="https://github.com/Nikhilesh1902">< AiFillGithub /></Link>
              <Link href="https://www.instagram.com/nikhilesh_19.02/"><AiOutlineInstagram /></Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-4xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Creative and curiosity-driven Graphic Designer eager to learn, contribute to team success through 
            hard work and coding skills. I use a creative approach to problem solve. 
            I am an effective and articulate communicator with all levels of employees.
            </p>
          </div>
          <br/>
          <br/>
          <br/>
          <div >
            <h3 className="text-4xl py-1 dark:text-white ">Skills</h3>
            <div className="flex align-center gap-[1vw]">
              <DiIllustrator className="text-[white] text-cyan-200 text-[20vh]"/>
              <DiPhotoshop className="text-[white] text-cyan-200 text-[20vh]"/>
              <DiPython className="text-[white] text-cyan-200 text-[20vh]"/>
              <p className="text-[white] text-cyan-200 text-[15vh]">C++</p>
              <DiCss3 className="text-[white] text-cyan-200 text-[20vh]"/>
              <DiJava className="text-[white] text-cyan-200 text-[20vh]"/>
              <p className="text-[white] text-cyan-200 text-[15vh]">C</p>
              <AiFillHtml5 className="text-[white] text-cyan-200 text-[20vh]"/>
              
            </div>  
            </div> 
          <br/>
          <br/>
          <br/>
            <div>
            <h3 className="text-4xl py-1 dark:text-white ">Interests</h3>
            <br/>
            <div className="flex flex-col align-center gap-[1vw]">
              <div className="bg-[] shadow-2xl  w-[15vw]">

              <p className="text-xl  text-teal-600"> 
                Graphic Designing
                </p>
              </div>
              <div className="bg-[] shadow-2xl w-[15vw]">

              <p className="text-xl  text-teal-600"> 
                Web Development
                </p>
              </div>
              <div className="bg-[] shadow-2xl  w-[15vw]">

              <p className="text-xl  text-teal-600"> 
                Coding
                </p>
              </div>
              <div className="bg-[] shadow-2xl  w-[15vw]">

              <p className="text-xl  text-teal-600"> 
                Music
                </p>
              </div>
            </div>  
            </div>         
          <br/>
          <br/>
          <br/>
          <div >
            <h3 className="text-4xl py-1 dark:text-white ">Certificates</h3>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg "
                width={"100%"}
                height={"90%"}
                layout="responsive"
                src={c1}
                />
              </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg "
                width={"100%"}
                height={"90%"}
                layout="responsive"
                src={c2}
                />
              </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg "
                width={"100%"}
                height={"90%"}
                layout="responsive"
                src={c3}
                />
              </div>
              
              <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg "
                width={"100%"}
                height={"90%"}
                layout="responsive"
                src={c5}
                />
            </div>
          </div>
                </div>
          
        </section>
        
        
      </main>
    </div>
  );
}
